### PR TITLE
fixes #57 by checking event details and setting overriding open

### LINKED ISSUE #57: Support for cmd+click open in new window
@pateketrueke thank you for the great work on YRV. We've heavily used it with that.us (github.com/thatconference/that.us).

I don't know if I am doing something wrong, or if it's just not supported but is there a way to support cmd+click where you open that link in a new window?

Thanks!
Clark

### PR DESCRIPTION
**Pull request by csell5**
Since we're preventingDefault I went down the path of adding a variable to track if the user requested to force open in a new tab. Then based on that reuse the existing logic when we set `open` on Link.

fixes #57

### CODE REVIEW

**Review by pateketrueke — CHANGES_REQUESTED** [review]
I think we should remove the `|preventDefault` from the markup as we're going to handle that by hand.

Inside the `if()` you added only doing a `return` would be enough, after that calling the `e.preventDefault()` would keep stuff below working.

Please try those changes, thank you.

**Comment by csell5** [comment]
🤦‍♂️ yea that's a much cleaner approach... On it.

File: src/lib/Link.svelte [hunk 1]
```diff
@@ -53,20 +53,21 @@
   // this will enable `<Link on:click={...} />` calls
   function onClick(e) {
     // user used a keyboard shortcut to force open link in a new tab
-    let userOpen = false;
     if (e.metaKey || e.ctrlKey || e.button !== 0) {
```
Comment (pateketrueke) [inline src/lib/Link.svelte:56]: this should also check if  `e.target.tagName === 'A'` to skip buttons

**Review by pateketrueke — CHANGES_REQUESTED** [review]

File: src/lib/Link.svelte [hunk 2]
```diff
@@ -53,20 +53,21 @@
...
       else if (go === 'fwd') window.history.forward();
       else window.history.go(parseInt(go, 10));
       return;
     }
 
-    if ((!fixedHref && href !== '') || userOpen) {
-      if (open || userOpen) {
+    if (!fixedHref && href !== '') {
+      if (open) {
         console.log('open');
```
[the remark this answers is not in the document]
Comment (csell5) [reply src/lib/Link.svelte:71]: My bad on that. Missed it.

**Comment by csell5** [comment]
Fixed up and rebased down to just 1 commit.

File: src/lib/Link.svelte [hunk 3]
```diff
@@ -52,6 +52,13 @@
 
   // this will enable `<Link on:click={...} />` calls
   function onClick(e) {
+    // user used a keyboard shortcut to force open link in a new tab
+    if (e.metaKey || e.ctrlKey || e.button !== 0 || e.target.tagName === 'A') {
```
Comment (pateketrueke) [inline src/lib/Link.svelte:56]: The logic here should  be `if (e.target.tagName === 'A' && (e.metaKey || e.ctrlKey || e.button !== 0)) return;` in order to skip those events on links only.

Also i'm not sure if this change can be covered by our e2e tests 🤔

**Review by pateketrueke — CHANGES_REQUESTED** [review]

File: src/lib/Link.svelte (hunk 3 above)
Comment (csell5) [reply src/lib/Link.svelte:56]: Source updated. I also added button as a check and then made it a nested if just as it was a bit more readable and less error prone. I have thoughts about the e2e but I'm going to drop that on the main thread.

**Comment by csell5** [comment]
re: e2e testing https://github.com/pateketrueke/yrv/pull/58#discussion_r522590921

Few thoughts, mind you I'm not familiar with the framework you're using.

* You could easily test the logic if you wanted to introduce a unit testing framework. I think in the case it's a completely valid situation because you're not trying to test if the browser knows what to do. Especially as all we're doing here is returning out and letting the default actions occur.

* I've recently been playing with cypress.io, found this bit https://docs.cypress.io/guides/references/trade-offs.html#Multiple-tabs which I think also states the problem pretty well.

* I did also notice that you're testing page isn't testing buttons. Not sure if that was intention or just overlooked. I know I personally use the button in a few places.

**Comment by pateketrueke** [comment]
Good job, actually for the e2e thing I think it will work.

I'll merge this and then add the required test for this feature, thank you!

File: src/lib/Link.svelte [hunk 4]
```diff
@@ -52,6 +52,15 @@
 
   // this will enable `<Link on:click={...} />` calls
   function onClick(e) {
+    // user used a keyboard shortcut to force open link in a new tab
+    if (e.target.tagName === 'A' || e.target.tagName === 'BUTTON') {
```
Comment (pateketrueke) [inline src/lib/Link.svelte:56]: It is possible to middle-click a button that opens in a new tab? If that's true then the first-level `if()` is not longer needed.

**Review by pateketrueke — APPROVED** [review]

**Comment by csell5** [comment]
I was really happy to help sorry about going back and forth so many times on a few dumb things.

Keep up the great work!

**Comment by pateketrueke** [comment]
> I know I personally use the button in a few places.

I'm still confused about this, check my comment in the code. 🤔

File: src/lib/Link.svelte (hunk 4 above)
Comment (csell5) [reply src/lib/Link.svelte:56]: ya know I was just following the lead based on what was presented with Link and my own usage.. maybe I was thinking about it wrong.. let me find a few sites and do a bit more homework.

Comment (csell5) [reply src/lib/Link.svelte:56]: ok, I think you're correct, nice catch.. I was just looking through the different things on github and true buttons don't behave like that... let me update.

**Comment by csell5** [comment]
ok I updated to remove that button check back to like you originally suggested.

**Review by pateketrueke — APPROVED** [review]

**Comment by pateketrueke** [comment]
Awesome, thank you!
